# Generated by Django 3.2.18 on 2023-04-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao_y', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicaoy',
            old_name='semetre',
            new_name='semestre',
        ),
    ]
